Bump c.xmltestreport to 2.0.2 (fixes Plone 5 tests):
This fixes

```
TypeError: test_failure() got an unexpected keyword argument 'stdout'
```

when running collective.xmltestreport with a version of
zope.testrunner >= 5.1 (which is the case for some Plone 5 buildouts).